### ISSUE TITLE
Reset Interactive

### ISSUE THREAD

**Issue by SeriousM** [lukebuehler/CShell#2]
Hi, I really love your CS-Hell :smile:
I missing a feature that would help a lot: reset the interactive shell.
reason: i do not want to re-open the app just for doing that.

A Shell.Repl.\* function would be enough for the moment.

TY!!

**Comment by lukebuehler** [comment]
I agree! This is a very much needed feature. I'll add it with the next iteration.

**Comment by mikefayer** [comment]
Just found this today via hackernews and want to add that I love this, already getting great use out of it. So far this is the only missing feature!

**Comment by lukebuehler** [comment]
k, will look into this. Nice to see CShell get some love.

**Comment by pjkrill** [comment]
Would you be interested in an interview about CShell, for a possible news story?

Paul Krill
InfoWorld

**Comment by lukebuehler** [comment]
Sure! Contact me at my email: lukas.buehler@gmail.com

**Comment by lukebuehler** [comment]
This is done
