### ISSUE TITLE
Interactive Editor

### ISSUE THREAD

**Issue by jeffpatton1971** [lukebuehler/CShell#21]
some of the expected basic text editing functions don't appear to work, for example:

At the end of the line hitting the home key should take me to the start of the line, that does not in fact happen.

If i'm typing some code and I only wish to select the first portion of the text, typically I will cursor over then hit shift+home which selects to the start of the line. That is the expected behavior, what happens when I do this I get kicked to the end of the line.

This seems odd to me, if this is supposed to happen just let me know so I can adjust my work flow.

Thanks!

**Comment by krispharper** [comment]
Oops, I just opened a new issue without reading yours. Looks like we have the same question.

https://github.com/lukebuehler/CShell/issues/22

**Comment by lukebuehler** [comment]
this is a bug, will fix it in #22
