### ISSUE TITLE
Home key acts like end key

### ISSUE THREAD

**Issue by krispharper** [lukebuehler/CShell#22]
I noticed that in the REPL, the home key behaves like the end key.

In [CSRepl.xaml.cs](https://github.com/lukebuehler/CShell/blob/master/Src/CShell/Modules/Repl/Controls/CSRepl.xaml.cs), this code explicitly does this.

```
if(key == Key.Home || key == Key.End)
{
    MoveCaretToEnd();
    keyEventArgs.Handled = true;
    return;
}
```

So it appears to be intentional. But I think it's a standard behavior that the home key moves to the beginning of the line. Indeed, in Scratchpad, this is the behavior.

What's the reasoning behind this?

**Comment by lukebuehler** [comment]
This is indeed a bug in the REPL. The keys have to be handled so that the cursor cannot jump to a location before the prompt cursor `>`, but not of course, like it does now, to the end.
