### ISSUE TITLE
Allow matching on partial words combined with camel case for autocompletion (Resharper style)

### ISSUE THREAD

**Issue by RedwoodForest** [lukebuehler/CShell#25]
One of the biggest issues I find using CShell along side my IDE is that autocompletion behaves significantly differently in CShell than in Visual Studio + Resharper. This means that I must keep the context in the back of my mind whenever I'm using CShell alongside VS + Resharper or I try to enter text that will autocomplete in Resharper but not in CShell. Then when I inevitably mess this up my mind gets thrown off the code I'm writing and I have to go back and fix it.

I wanted to open this issue and get your thoughts on it and learn about anything you have planned before writing up a complete proposal for a revised completion algorithm.

Should feature requests for auto-completion be filed here or at the Avalon Edit project?

A good example of something I like about the Resharper algorithm (and what throws me off when when using CShell) is that if I'm trying to match DateTime, in Resharper I can enter `DT`, see that there are a lot of possible completions, and continue on to type `DTime` which will filter these down to just a couple completions, one of which is DateTime, which is really nice when just the first letters of the words does not filter the list enough for my taste. 

I'm willing to write up a more complete and algorithmic description of the Resharper behavior as I understand it if that would be helpful, but I wanted to make sure this was a plausible change first.

I really like CShell and am hoping to completely replace LINQPad with it. It really is a great project and I appreciate all the work you're putting into it.

**Comment by lukebuehler** [comment]
@lawrencejohnston will close as wontfix since this is really work that needs to be done on the AvalonEdit project. I recommend opening this issue there, please let me know when you have done that so I can chime in on the conversation.

**Comment by RedwoodForest** [comment]
Opened as https://github.com/icsharpcode/AvalonEdit/issues/3

**Comment by lukebuehler** [comment]
@lawrencejohnston Thanks!
