### ISSUE TITLE
Match camelCase as well as PascalCase by first word letters when autocompleting

### ISSUE THREAD

**Issue by RedwoodForest** [lukebuehler/CShell#26]
This is another example of an improvement inspired by my experience with Resharper as discussed in #25.

Currently if I have an autocompletion candidate `SomeLongName` then `sln` will match it because it matches the first letter of each word. If I have a candidate `anotherLongName` however `aln` will not match it because it's in camel case instead of pascal case.

Examples of names you might want to autocomplete that would be likely to be in camel case include variables and fields.

It would be great if autocompletion worked with camel case names as well as it does with pascal case names.

**Comment by medmondson** [comment]
Do I understand that what you are asking for is autocompletion to be case sensitive?

**Comment by RedwoodForest** [comment]
No, I don't think that's what I'm asking for. Let me clarify by giving a concrete example in CShell.

Enter the following in a CShell script and execute it:

```
public class SomeType {
    public static string multiWordMember;

    public static string MultiWordMember {get; set;}
}
```

We now have a type with two static members, one in camel case and one in pascal case.

Now in the REPL enter `SomeType.mwm` and look at the suggested autocompletions. I would expect the autocompletions to include both `multiWordMember` and `MultiWordMember` because in both cases `mwm` matches the first letter of each word in the member, but in fact only `MultiWordMember` is matched. I believe both members should be matched.

**Comment by bc3tech** [comment]
I’d argue for not naming things w/ only differing case. Ultra-confusing.

Said another way: if it hurts when you bang your head against the wall, don’t do that.

Now, if _multiWordMember and MultiWordMember weren’t matched, I’d be on board w/ the change…

**Comment by lukebuehler** [comment]
Hmm, I see. Just looked how ReSharper would handle your example. It indeed knows how to match the different cases differently. The ReSharper ["CamelHumps"](http://www.jetbrains.com/resharper/webhelp/Navigation_and_Search__CamelHumps.html) matching is, of course, quite sophisticated. The [completion algo is actually part of AvalonEdit](https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/CodeCompletion/CompletionList.cs#L240), so we would need to improve it there.

For now, I'm quite happy with the completion algo, while I agree it could be better. We need to first work on fixing other completion problems like #4.

**Comment by RedwoodForest** [comment]
@bc3tech The members are named the same with different case in my example only to make the difference in behavior for pascal case vs camel case obvious. You oculd just as easily rename them to `multiWordMemberField` and `MultiWordMemberProperty` and still attempt to complete using `mwm` and have the same issue.

If it helps you could restate my request as follows:

I have a variable named `someVariableName` (I hope we can agree that it's reasonable to name a variable using camel case). I'm trying to autocomplete it, so I enter `svn`, which matches the first letter of each word in the variable name. It doesn't match. I would like it to match.

The fact that `svn` would match `SomeVariableName` in the current implementation is supporting evidence for why this seems like a reasonable request.

@lukebuehler Thanks for your input, that makes sense. Should this issue be filed over at Avalon Edit as well? Since it's part of Avalon Edit it's probably not in your hands, but if I were to look at addressing it over there would you consider it to be a change for the better?

**Comment by lukebuehler** [comment]
@lawrencejohnston, yes I would post this issue there as well. Since it would have to be changed in AvalonEdit.

**Comment by medmondson** [comment]
Does these mean we're happy to close?

**Comment by lukebuehler** [comment]
@lawrencejohnston will close as wontfix since this is really work that needs to be done on the AvalonEdit project. I recommend opening this issue there, please let me know when you have done that so I can chime in on the conversation.

**Comment by RedwoodForest** [comment]
Opened as https://github.com/icsharpcode/AvalonEdit/issues/1 and submitted pull request.
