### ISSUE TITLE
dynamic support

### ISSUE THREAD

**Issue by rushfrisby** [lukebuehler/CShell#29]
Is dynamic not supported? I just tried this but am getting an error.

using System.Dynamic;
dynamic source = new ExpandoObject();
source.Property1 = "test";
Console.WriteLine(source.Property1);

(2,0): error CS1525: Unexpected symbol `dynamic'

**Comment by lukebuehler** [comment]
Yes unfortunately the mono elevator did not support it. Now we switched to Roslyn, which also doesn't support it. So this will not work in the foreseeable future until the Roslyn team implements it.
