### ISSUE TITLE
Visibility of object instance for Intellisense

### ISSUE THREAD

**Issue by toxonaut** [lukebuehler/CShell#43]
When I instantiate a class or a method (using an alpha) within a Shell.TryEvaluateFile(@"testscript.cs") command in OnOpened(), then the objects are available for intellisense in c# Interactive, but not in the code editor.

**Comment by toxonaut** [comment]
Its actually also true when the Shell.TryEvaluateFile command is executed from the code window. Objects instatiated in the script file are only "seen" by intellisense in the interactive window.

**Comment by lukebuehler** [comment]
@toxonaut, this is indeed a bug. However, the way evaluation of classes are handled and integrated into code completion will change substantially with the next release (Roslyn and ScripCS integration).

Classes and instances will never be automatically visible from the script editor, even in the next version. The idea being that we'll want to be compatible with ScriptCS.

But you will be able to reference an external file like this, which the code completion will pick up:

MyClass.cs

```
public class Foo { public int Bar; }
```

MyScript.csx

```
#load "MyClass.cs"
//here code completion will work
var f = new Foo();
var f.Bar = 10;
//etc
```

**Comment by toxonaut** [comment]
Hi Luke

Thanks for the quick answer. I'm looking forward to the next release! The
#load should solve the problem.
Keep up the good work!
Cheers,
Martin
