### ISSUE TITLE
Save references

### ISSUE THREAD

**Issue by tpluscode** [lukebuehler/CShell#47]
Is it possible to remember assembly refrences so that they are restored when CShell workspace is opened again?

**Comment by lukebuehler** [comment]
Yep, it is possible, by default it should already work. Open the CShell file and you'll see the closing code. Is it not working for you?

**Comment by tpluscode** [comment]
Hm it did not the first time but it would seem that something odd had happened before. I pinned the Workspace Explorer window but when I first restarted CShell it was again collapsed.

Anyways it did indeed work the second time so maybe some rare quirk or my mistake.
