### ISSUE TITLE
version 0.1.2 targeting .net 4.5 excludes Windows 2003/XP and previous

### ISSUE THREAD

**Issue by IBIT-ZEE** [lukebuehler/CShell#52]
version 0.1.2 targeting .net 4.5 excludes Windows 2003/XP and previous
Please re-target to .net 4.0, at least until MS decides to launch a .net runtime 4.5 to these OS... 
or maybe someone come with a fix/package to allow this... 
maybe the "Evil Empire" in .net 5.0 contemplates at least NT5 again... ( ;-) )

**Comment by lukebuehler** [comment]
The editor (avalon edit), and a lot of the NRefactory stuff (code completion) requires .net 4.5. So there's no easy way to tarket .net 4.0.

**Comment by IBIT-ZEE** [comment]
I use Windows 7, 8, 2008, 2012, etc.
but my target machines around 70% are XP... and maybe a 5% of Windows Sever
2003...

Theres a lot of people and PC using XP/2003, .net 4.0... 

if you launch a .net 4.0 compiled binary with these fixes please send me a
link... 

Thanx, ZEE

**Comment by lukebuehler** [comment]
I understand, but it's not feasible to maintain a .net 4.0 version. In the beginning we did that, but we had to build all the libraries with 4.0 support, which was a lot of work.
