### ISSUE TITLE
Part of the VS Debugger

### ISSUE THREAD

**Issue by SeriousM** [lukebuehler/CShell#6]
Hi!

CSHell looks awesome but I would love to see it as an extension of the VS-Debugger because lambda expression is not supported there.
Would that be possible?

Cheers

**Comment by lukebuehler** [comment]
I don't really see that happening for CShell because the focus is more a stand-alone project. However this feature could be created as a plugin for the debugger using directly Mono.CSharp (which CShell uses) or Roslyn.
