### ISSUE TITLE
Error with multiplication operator

### ISSUE THREAD

**Issue by Cefi** [lukebuehler/CShell#62]
Hi

Please run the following code in CShell:
var x = 7;
x;        // -> print out: 7, OK
3 \* x    // -> print out: 21, OK
x \* 3;   // -> print out: (1,5): error CS1525: Unexpected symbol `3'   (???)

With kind regards
Ceferino Garcia
DENKFABRIK GmbH

**Comment by theelderwand** [comment]
This doesn't seem to reproduce in the C# interactive

**Comment by lukebuehler** [comment]
Works now in the latest version on the dev branch. Since we switched to roslyn.
