### ISSUE TITLE
Please add extension to Visual Studio Extension gallery

### ISSUE THREAD

**Issue by weitzhandler** [lukebuehler/CShell#63]
Hi,

I wish this extension could work within Visual Studio as a docked or floating tab or document.
I this a hard thing to implement?
Perhaps it's even possible to reuse the built-in C# syntax highlighting features.

**Comment by lukebuehler** [comment]
Thanks for the feedback!

But, better use C# interactive for this: 
https://www.microsoft.com/en-us/download/details.aspx?id=34685

As soon as roslyn is released the C# interactive should be included in VS 2015. 

Also, integrating CShell into VS would be quite a pain, better create a new plugin from scratch, but as I said roslyn got you covered.
