### ISSUE TITLE
DumpGrid omits property named "Name" (v0.1.2.30750)

### ISSUE THREAD

**Issue by jrnail23** [lukebuehler/CShell#72]
This works as expected:

``` CSharp
new[]{new{ FavoriteColor="Blue", FirstName="James"}}.DumpGrid()
```

Dumping the following:

| FavoriteColor | FirstName |
| --- | --- |
| Blue | James |

But this doesnt:

``` CSharp
new[]{new{ FavoriteColor="Blue", Name="James"}}.DumpGrid()
```

Instead, it omits the Name property, outputting the following:

| FavoriteColor |
| --- |
| Blue |

**Comment by lukebuehler** [comment]
Thanks, this is fixed in the latest dev branch.

**Comment by lukebuehler** [comment]
![missingfields](https://cloud.githubusercontent.com/assets/542828/9175332/19d0d846-3f53-11e5-9f22-77ee7c1c5815.PNG)

**Comment by jrnail23** [comment]
:+1:
