### ISSUE TITLE
Upgrade CShell to also run F# scripts

### ISSUE THREAD

**Issue by ashleydavis** [lukebuehler/CShell#78]
It would be fantastic if CShell could also run F# scripts!

**Comment by lukebuehler** [comment]
I was thinking about this for a long time, and initially planned for CShell to support this eventually. However, at this point I'm tending to think this should be a separate project.

Especially considering [Ionide](http://ionide.io/) for Atom which makes it essentially a "CShell" for F# in the Atom editor. So there's already a lot momentum in this direction...
