### ISSUE TITLE
Upload as Chocolatey package

### ISSUE THREAD

**Issue by engstrom** [lukebuehler/CShell#8]
I think this would make a great package for [Chocolatey](https://chocolatey.org/).

**Comment by lukebuehler** [comment]
Thanks for the input, will look into it. As there's some more interest in CShell now, I'll fix some bugs and then submit it to Chocolatey.

**Comment by ctolkien** [comment]
:+1:  - first thing I tried to do was install from Choco.

**Comment by philbritton** [comment]
:+1:

**Comment by bc3tech** [comment]
I did this today for the betterment of the project. @lukebuehler, I tweeted at you first but then decided to move forward. If you'd like me to make you a co-maintainer just say the word!

cinst cshell

**Comment by lukebuehler** [comment]
@bc3tech, thanks & appreciate it! You must have written to the wrong twitter account mine is @lukasbuhler.

Sure, adding me as a maintainer would be good, then I can upload a new package when the binaries change. My account is: lukebuehler

**Comment by bc3tech** [comment]
my bad - I took the @ name from the cshell.net website and thought that was your twitter acct. 
I've added you as a maintainer now! (mark this bad boy resolved) :)

**Comment by lukebuehler** [comment]
thanks @bc3tech!

**Comment by masaeedu** [comment]
@lukebuehler Hi Luke. I think recent changes to the Chocolatey API have broken the package. Fortunately Rob has provided some feedback on how to fix on the [package page](https://chocolatey.org/packages/CShell/0.1.2.2).

**Comment by lukebuehler** [comment]
Thanks, I'm working to finish up the current version and release a package again
